---
# Gather packages
- hosts: vhaskell
  sudo: yes
  gather_facts: no
  
  tasks:
  - name: ensure packages are installed
    action: apt pkg=$item
    with_items:
        - git
        - mercurial
        - postgresql
        - libpq-dev
        - python-psycopg2
        - haskell-platform
        - python
        - python-pip
  
  - name: install custom bash profile
    action: template src=templates/bash_profile dest=/home/vagrant/.profile

- include: playbooks/supervisord/supervisord.yml
- include: playbooks/postgresql/postgresql.yml
- include: playbooks/cabal/cabal.yml